version: '2'
services:
  spark:
    image: jupyter/pyspark-notebook
    container_name: spark
    ports:
      - 8888:8888
    volumes:
      - ./docker_data/spark-data:/home/jovyan/work


  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./docker_data/cassandra-data:/var/lib/cassandra

  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock: 
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      -  ./docker_data/elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes:
      - ./docker_data/zk-data:/var/lib/zookeeper/data
      - ./docker_data/zk-txn-logs:/var/lib/zookeeper/log 

  redis:
    image: redis
    ports: 
      - "6379:6379"
  
    clickhouse:
    image: yandex/clickhouse-server:latest
    hostname: clickhouse
    container_name: clickhouse
    ports: 
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      #CLICKHOUSE_DB: Big_analytics__
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    # depends_on:
    #   - "zookeeper"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 604800000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 302400000
    volumes:
      - ./docker_data/kafka-data:/var/lib/kafka/data 
